name: Deploy Code
on:
  push:
    branches: [ "main", "stage" ]

permissions:
  contents: read
  

jobs:
  deploy-prod:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Pull Updated Code
      run: |
        cd /home/odoo/odoo && git pull origin main

    - name: Updating Prod Server
      run: |
        cd /home/odoo/odoo && export ODOO_IMAGE=prod && sh scripts/update_server.sh

    - name: Upgrade Addons
      run: |
        docker run --rm --net odoo_odoo -v odoo_odoo-data:/var/lib/odoo -iu root --link db:db ${{vars.ODOO_IMAGE}} click-odoo-update -c /etc/odoo/odoo.conf -d ${{vars.MAIN_DB}}

  deploy-stage:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/stage'
    steps:
    - name: Pull Updated Code
      run: |
        cd /home/odoo/stage && git pull origin stage

    - name: Updating Stage Server
      run: |
        cd /home/odoo/stage && export ODOO_IMAGE=stage && sh scripts/update_server.sh

    - name: Upgrade Addons
      run: |
        docker run --rm --net stage_odoo -v stage_odoo-data:/var/lib/odoo -iu root --link stage_db:db ${{vars.ODOO_STAGE_IMAGE}} click-odoo-update -c /etc/odoo/odoo.conf -d ${{vars.STAGE_DB}}
      
