name: Push & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy With Latest Code
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          USERNAME: ${{secrets.SSH_USERNAME}} # User of the server you want to ssh into
          # PASSWORD: ${{secrets.SSH_PASSWORD}} # SSH server user password
          KEY: ${{secrets.SSH_KEY}}
          PORT: ${{secrets.SSH_PORT}} # SSH server port
        with:
          script_stop: true # Will stop build incase of any failures
          script: |
            cd /home/odoo/odoo
            sh scripts/update_server.sh
